export default Object.freeze({
    SET_FEED_FETCHING_STATE: 'SET_FEED_FETCHING_STATE',
    INITIALIZE: 'INITIALIZE',
    SET_ONLINE_STATUS: 'SET_ONLINE_STATUS',
    SET_AUTH_FETCHING_STATE: 'SET_AUTH_FETCHING_STATE',
});